language: node_js
node_js:
  - "10"
dist: trusty # needs Ubuntu Trusty
sudo: required
before_install:
  - npm install -g npm@latest
install:
  - npm ci
addons:
  chrome: stable # install chrome stable
cache:
  yarn: true
  directories:
    - $HOME/.npm
before_script:
    - npm run lint
script:
  - npm run coverage
after_success:
  - npm run coveralls
